### ISSUE TITLE
Rack v1: plugin.json does not define tags for modules

### ISSUE THREAD

**Issue by cschol** [expertsleepersltd/vcvrack-encoders#1]
This is not super critical, but the manifest validation script run on `plugin.json` noticed that there are no tags defined in your manifest for any of the modules:

```
Validating ExpertSleepers-Encoders
ExpertSleepers-Encoders-8CV: missing tags: no tags defined for module
ExpertSleepers-Encoders-8GT: missing tags: no tags defined for module
ExpertSleepers-Encoders-ES5: missing tags: no tags defined for module
ExpertSleepers-Encoders-ES40: missing tags: no tags defined for module
ExpertSleepers-Encoders-SMUX: missing tags: no tags defined for module
```

Tags can be strings as defined in the following file:
https://github.com/VCVRack/Rack/blob/v1/src/plugin.cpp#L534

I'll go ahead with the integration. You can add it in the next round of updates if you want.

**Comment by expertsleepers** [comment]
Added tags in version 1.1.0.
