### ISSUE TITLE
Wrong output on Port 8 of GT8?

### ISSUE THREAD

**Issue by stoermelder** [expertsleepersltd/vcvrack-encoders#2]
Hi os,
my setup is a ES-5 hooked up to channels 7/8 of an ES-3. When I connect a single port of the 8GT module in Rack everything is fine. When I connect multiple ports on the 8GT everything is fine until a connect something on port 8 in Rack, then all output ports on the ES-5 are messed up. 
I haven't checked your code yet and I don't have an expander for the ES-5, but I think there is something wrong with the calculation on the last channel of GT8.

**Comment by stoermelder** [comment]
It looks ok in the GT8 code, I guess the problem must be in the code of the ES-5 encoder module...

**Comment by expertsleepers** [comment]
Are you on mac or PC?

There's a related thread here: https://www.muffwiggler.com/forum/viewtopic.php?p=3111001#3111001

**Comment by stoermelder** [comment]
I‘m on Windows. It seems I‘m having the same issue described in the forum thread. How can I assist you to debug this issue?

I‘m using an RME Digiface USB and and I also adjusted the output Levels in TotalMix to get it working for outputs 1-7 on the ES-5, with unity gain no success.

**Comment by expertsleepers** [comment]
Seems that Rack on Windows is problematic. Testing with my RME UCX:
- mac, Silent Way in Live -> OK
- mac, VCV -> OK
- windows, Silent Way in Live -> OK
- windows, VCV -> not OK

I'll have a look at the code and maybe talk to Andrew.

**Comment by stoermelder** [comment]
https://github.com/VCVRack/Rack/issues/1539

**Comment by stoermelder** [comment]
I got it working without changing anything in Rack. I played around with RME's TotalMix yesterday and tried every setting I could imagine. I will try to find out whats going on here...

**Comment by stoermelder** [comment]
Any news on this? I got an ESX-GT8 today and it is totally unusable on port GT2 in official build of Rack. I'm using my custom build with the mentiod change which works fine.
https://github.com/VCVRack/Rack/issues/1539#issuecomment-525383568

**Comment by expertsleepers** [comment]
closing: https://github.com/VCVRack/Rack/issues/1539#issuecomment-612875502
