### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [expertsleepersltd/vcvrack-encoders#3]
Just a quick question, as I don't see it mentioned anywhere.
Your project is licensed under MIT, but does that include the graphics too? Or are those supposed to be in a different license?
Thanks!

**Comment by expertsleepers** [comment]
You mean the plain orange panels with text on them? I don't really see an issue with people using those for free.

Is there another question behind your question? What were you wanting to do with the graphics exactly?

**Comment by falkTX** [comment]
> Is there another question behind your question? What were you wanting to do with the graphics exactly?

I ask this for packaging.
I am creating a little application that contains your modules, and intention is to push it to Linux repositories (Ubuntu, Arch, etc) soon. They require all licensing to be as clear as possible.
You can see my investigation on this so far in here https://github.com/DISTRHO/Cardinal/blob/main/doc/LICENSES.md#artwork--panel-licenses

Now to come back to the main question, can we assume the artwork to be under MIT then? The same license as the code?

**Comment by expertsleepers** [comment]
Yes, the artwork is MIT. FWIW, 'Expert Sleepers' is trademarked.

I see you've been asking the same question of various developers. It would be helpful if in your original post you said "Hello, I'm working on this open source project (link) and I'd like to pull in your source code/artwork, so I have this question".

**Comment by falkTX** [comment]
> I see you've been asking the same question of various developers. It would be helpful if in your original post you said "Hello, I'm working on this open source project (link) and I'd like to pull in your source code/artwork, so I have this question".

True yes, but it is also a valid question for anyone else that comes after me that also does something similar.
It is not specific to my project, anyone doing packaging in general would have the same questions.
VCVRack has just been very abrasive against having it in regular linux distros, so it never happened (yet).

I will keep that in mind though, thank  you.
